/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalIdRouteImport } from './routes/animal/$id'

const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalIdRoute = AnimalIdRouteImport.update({
  id: '/animal/$id',
  path: '/animal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/animal/$id': typeof AnimalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/animal/$id': typeof AnimalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/animal/$id': typeof AnimalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animals' | '/animal/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animals' | '/animal/$id'
  id: '__root__' | '/' | '/animals' | '/animal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRoute
  AnimalIdRoute: typeof AnimalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animal/$id': {
      id: '/animal/$id'
      path: '/animal/$id'
      fullPath: '/animal/$id'
      preLoaderRoute: typeof AnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRoute,
  AnimalIdRoute: AnimalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
